name: .NET Core

on:
  push:
    branches: 
      - master
  
jobs:
  gated:
    name: test, build, pack and publish
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100          
      - name: test
        working-directory: ./src      
        run: dotnet test
#       run: dotnet build --configuration Release
