name: anyservice ci

on:
  push:
    branches: 
      - master
  
jobs:
  gated:
    name: test, build, pack and publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      
      - name: Checkout master branch
        uses: actions/checkout@master
        with:
          dotnet-version: 3.1.100          

      - name: Test
        working-directory: ./src      
        run: dotnet test

      - name: Build
        working-directory: ./src/AnyService
        run: dotnet build --configuration Release
      
      - name: Pack nuget package
        working-directory: ./src/AnyService
        run: dotnet pack --configuration Release
      
#       - name: Publish nuget
#         working-directory: ./src/AnyService/bin/Release/
#         run: |
#            curl -vX PUT -u "[user]:${{ secrets.GHPackagesToken }}" -F package=anyservice.nupkg https://nuget.pkg.github.com/[user]/
#            done
#         shell: bash
