name: anyservice ci

on:
  push:
    branches:
      - main

jobs:
  continunous_delivery:
    name: build, test & deploy

    defaults:
      run:
        working-directory: ./src

    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Checkout main branch
        uses: actions/checkout@main
        with:
          dotnet-version: 7.0.x

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Test AnyService.Utilities
        run: dotnet test ./AnyService.Utilities.Tests/AnyService.Utilities.Tests.csproj --verbosity normal --configuration Release --no-build /p:CollectCoverage=true

      - name: Test AnyService.Core.Tests
        run: dotnet test ./AnyService.Core.Tests/AnyService.Core.Tests.csproj --verbosity normal --configuration Release --no-build /p:CollectCoverage=true /p:Exclude=""[AnyService.Utilities]*""

      - name: Test AnyService.Tests
        run: dotnet test ./AnyService.Tests/AnyService.Tests.csproj --verbosity normal --configuration Release --no-build /p:CollectCoverage=true /p:Exclude=""[AnyService.Utilities]*%2c[AnyService.Core]*""

      - name: Test AnyService.AnyServiceModules.EntityFrameworkTests
        run: dotnet test ./AnyServiceModules/EntityFramework/AnyService.EntityFramework.Tests/AnyService.EntityFramework.Tests.csproj --verbosity normal --configuration Release --no-build --filter ""category!=sql-server"" /p:CollectCoverage=true /p:Exclude=""[AnyService.Utilities]*%2c[AnyService.Core]*""

      - name: Publish AnyService.Utilities
        run: dotnet publish AnyService.Utilities/*.csproj --configuration Release

      - name: Publish AnyService.Core
        run: dotnet publish AnyService.Core/*.csproj --configuration Release

      - name: Publish AnyService
        run: dotnet publish AnyService/*.csproj --configuration Release

      - name: Publish AnyService.EntityFramework
        run: dotnet publish AnyServiceModules/EntityFramework/AnyService.EntityFramework/*.csproj --configuration Release

      - name: Publish AnyService.Events.RabbitMQ
        run: dotnet publish AnyServiceModules/AnyService.Events.RabbitMQ/*.csproj --configuration Release

      - name: Upload Artifacts - AnyService.Utilities
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AnyService.Utilities for publish
          path: ./src/AnyService.Utilities/bin/Release/netstandard2.1/publish/
          if-no-files-found: error

      - name: Upload Artifacts - AnyService.Core for publish
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AnyService.Core
          path: ./src/AnyService.Core/bin/Release/netstandard2.1/publish/
          if-no-files-found: error

      - name: Upload Artifacts - AnyService for publish
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AnyService
          path: ./src/AnyService/bin/Release/net7.0/publish/
          if-no-files-found: error

      - name: Upload Artifacts - AnyService.EntityFramework for publish
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AnyService.EntityFramework for publish
          path: ./src/AnyServiceModules/EntityFramework/AnyService.EntityFramework/bin/Release/net7.0/publish/
          if-no-files-found: error

      - name: Upload Artifacts - AnyService.Events.RabbitMQ for publish
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AnyService.Events.RabbitMQ for publish
          path: ./src/AnyServiceModules/AnyService.Events.RabbitMQ/bin/Release/netstandard2.1/publish/
          if-no-files-found: error

      # - name: pack Anyservice.Utilities nuget package
      #   working-directory: ./
      #   run: dotnet pack ./src/AnyService.Utilities/AnyService.Utilities.csproj --configuration Release --output ./nupkg --no-build --include-symbols  --include-source -p:SymbolPackageFormat=snupkg
      - name: pack Anyservice.core nuget package
        working-directory: ./
        run: dotnet pack ./src/AnyService.Core/AnyService.Core.csproj --configuration Release --output ./nupkg --no-build --include-symbols  --include-source -p:SymbolPackageFormat=snupkg
      # - name: pack Anyservice nuget package
      #   working-directory: ./
      #   run: dotnet pack ./src/AnyService/AnyService.csproj --configuration Release --output ./nupkg --no-build --include-symbols  --include-source -p:SymbolPackageFormat=snupkg
      # - name: pack Anyservice.easycaching nuget package
      #   working-directory: ./
      #   run: dotnet pack ./src/AnyServiceModules/EasyCaching/AnyService.EasyCaching/AnyService.EasyCaching.csproj --configuration Release --output ./nupkg --no-build --include-symbols  --include-source -p:SymbolPackageFormat=snupkg
      # - name: pack Anyservice.entityframework nuget package
      #   working-directory: ./
      #   run: dotnet pack ./src/AnyServiceModules/EntityFramework/AnyService.EntityFramework/AnyService.EntityFramework.csproj --configuration Release --output ./nupkg --no-build --include-symbols  --include-source -p:SymbolPackageFormat=snupkg
      # - name: pack Anyservice.litedb nuget package
      #   working-directory: ./
      #   run: dotnet pack ./src/AnyServiceModules/LiteDb/AnyService.LiteDb/AnyService.LiteDb.csproj --configuration Release --output ./nupkg --no-build --include-symbols  --include-source -p:SymbolPackageFormat=snupkg
      # - name: pack Anyservice.events.rabbitmq nuget package
      #   working-directory: ./
      #   run: dotnet pack ./src/AnyServiceModules/AnyService.Events.RabbitMQ/AnyService.Events.RabbitMQ.csproj --configuration Release --output ./nupkg --include-symbols  --include-source -p:SymbolPackageFormat=snupkg
      - name: Push packages to nuget
        working-directory: ./nupkg
        run: dotnet nuget push *.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
        env:
          nuget_api_key: ${{secrets.NUGET_DEPLOY_KEY}}
